const db = [
  {
    id: 1,
    name: 'Jake Knowles',
    avatar: '',
    country: 'Spanish',
    handicap: 12.8,
    wins: 2,
    current_season_standing: 1,
    current_season_points: 14,
  },
  {
    id: 2,
    name: 'Josh Craske',
    avatar: '',
    country: 'English',
    handicap: 20.8,
    wins: 0,
    current_season_standing: 2,
    current_season_points: 12,
  },
  {
    id: 3,
    name: 'Tom Mason',
    avatar: '',
    country: 'English',
    handicap: 28,
    wins: 0,
    current_season_standing: 3,
    current_season_points: 10,
  },
  {
    id: 4,
    name: 'Charlie Land',
    avatar: '',
    country: 'English',
    handicap: 28,
    wins: 0,
    current_season_standing: 4,
    current_season_points: 7,
  },
  {
    id: 5,
    name: 'Rory Kennedy',
    avatar: '',
    country: 'Ireland',
    handicap: 28,
    wins: 0,
    current_season_standing: 5,
    current_season_points: 6,
  },
  {
    id: 6,
    name: 'Lee Green',
    avatar: '',
    country: 'India',
    handicap: 32,
    wins: 0,
    current_season_standing: 6,
    current_season_points: 4,
  },
  {
    id: 7,
    name: 'Jake Williams',
    avatar: '',
    country: 'Jamaica',
    handicap: 36,
    wins: 0,
    current_season_standing: 7,
    current_season_points: 3,
  }
];

export default db;